### ISSUE TITLE
BAF heatplot error

### ISSUE THREAD

**Issue by insilicool** [uci-cbcl/PyLOH#4]
Hi,

I am having a recurrent bug when running BAF heatplot function.  Could you please help me identify the problem.

Thanks.

Traceback (most recent call last):
  File "/home/reveleig/github/PyLOH/PyLOH.py", line 110, in <module>
    args.func(args)
  File "/sb/home/reveleig/github/PyLOH/pyloh/postprocess/plot.py", line 49, in plot_BAF_heatmap
    plot_BAF_heatmap_by_segment(BAF_counts_j, seg_name_j, outheatmap_dir_name)
  File "/sb/home/reveleig/github/PyLOH/pyloh/postprocess/plot.py", line 67, in plot_BAF_heatmap_by_segment
    cbar = pyplot.colorbar(ticks=[0, color_max], orientation='vertical', shrink=0.78)
  File "/lb/project/mugqic/analyste_dev/software/python/Python-2.7.8/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2159, in colorbar
    ret = gcf().colorbar(mappable, cax = cax, ax=ax, *_kw)
  File "/lb/project/mugqic/analyste_dev/software/python/Python-2.7.8/lib/python2.7/site-packages/matplotlib/figure.py", line 1506, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, *_kw)
  File "/lb/project/mugqic/analyste_dev/software/python/Python-2.7.8/lib/python2.7/site-packages/matplotlib/colorbar.py", line 1318, in colorbar_factory
    cb = Colorbar(cax, mappable, *_kwargs)
  File "/lb/project/mugqic/analyste_dev/software/python/Python-2.7.8/lib/python2.7/site-packages/matplotlib/colorbar.py", line 894, in **init**
    ColorbarBase.**init**(self, ax, *_kw)
  File "/lb/project/mugqic/analyste_dev/software/python/Python-2.7.8/lib/python2.7/site-packages/matplotlib/colorbar.py", line 321, in **init**
    self.draw_all()
  File "/lb/project/mugqic/analyste_dev/software/python/Python-2.7.8/lib/python2.7/site-packages/matplotlib/colorbar.py", line 346, in draw_all
    self._config_axes(X, Y)
  File "/lb/project/mugqic/analyste_dev/software/python/Python-2.7.8/lib/python2.7/site-packages/matplotlib/colorbar.py", line 440, in _config_axes
    self.update_ticks()
  File "/lb/project/mugqic/analyste_dev/software/python/Python-2.7.8/lib/python2.7/site-packages/matplotlib/colorbar.py", line 371, in update_ticks
    ticks, ticklabels, offset_string = self._ticker()
  File "/lb/project/mugqic/analyste_dev/software/python/Python-2.7.8/lib/python2.7/site-packages/matplotlib/colorbar.py", line 591, in _ticker
    formatter.set_locs(b)
  File "/lb/project/mugqic/analyste_dev/software/python/Python-2.7.8/lib/python2.7/site-packages/matplotlib/ticker.py", line 523, in set_locs
    self._set_format(vmin, vmax)
  File "/lb/project/mugqic/analyste_dev/software/python/Python-2.7.8/lib/python2.7/site-packages/matplotlib/ticker.py", line 584, in _set_format
    loc_range_oom = int(math.floor(math.log10(loc_range)))
ValueError: math domain error

**Comment by yil8** [comment]
Hi,

Is it possible to email your *.PyLOH.heatmap.pkl to yil8@uci.edu ? I'd like to take a look to see if there is something wrong with the file.

Thanks
