### ISSUE TITLE
"Reason: 'IOError('bad message length',)'Preprocessing segment chr12_start_109725923_end_109726043 in pyloh "

### ISSUE THREAD

**Issue by ArshiyaG** [uci-cbcl/PyLOH#9]
Hey,
I ran PyLOH for tumor-normal samples and took almost 20 hours but with an error message given below . I also don't find the output files in th given path. 
Please help me 

"Reason: 'IOError('bad message length',)'Preprocessing segment chr12_start_109725923_end_109726043 in pyloh "

Thanks in Advance 
Arshiya

**Comment by yil8** [comment]
@ArshiyaG Sorry, but the information you provided is too little for me to give any feedback. Can you take a look at this issue https://github.com/uci-cbcl/PyLOH/issues/2 and reframe your problem here? Thanks

**Comment by ArshiyaG** [comment]
The below mentioned was the command given : 

python2 PyLOH.py preprocess /home/hg19.fa /root/Normal-NO.bam /root/Tumor-TO.bam Tumor-Normal --segments_bed /home/xgen-exome-research-panel-probesbe255a1532796e2eaa53ff00001c1b3c.bed --min_depth 20 --min_base_qual 10 --min_map_qual 10 --process_num 10 --WES

After preprocessing the segements, I got an error : Reason: 'IOError('bad message length',)'Preprocessing segment chr12_start_109725923_end_109726043 

Thanks in Advance
Arshiya

**Comment by yil8** [comment]
@ArshiyaG can you copy paste the full error message printed from screen? like https://github.com/uci-cbcl/PyLOH/issues/2
```python
Loading segments by 22 autosomes...
Preprocessing segment chr1_start_0_end_249250621...
Preprocessing segment chr2_start_0_end_243199373...
Preprocessing segment chr3_start_0_end_198022430...
Preprocessing segment chr4_start_0_end_191154276...
Preprocessing segment chr5_start_0_end_180915260...
Preprocessing segment chr6_start_0_end_171115067...
Preprocessing segment chr7_start_0_end_159138663...
Preprocessing segment chr8_start_0_end_146364022...
Preprocessing segment chr9_start_0_end_141213431...
Preprocessing segment chr10_start_0_end_135534747...
Traceback (most recent call last):
  File "/home/klrl262/miniconda/envs/bcbio-test/bin/PyLOH.py", line 110, in <module>
    args.func(args)
  File "/home/klrl262/miniconda/envs/bcbio-test/lib/python2.7/site-packages/pyloh/preprocess/run_preprocess.py", line 51, in run_preprocess
Preprocessing segment chr11_start_0_end_135006516...
    converter.convert()
  File "/home/klrl262/miniconda/envs/bcbio-test/lib/python2.7/site-packages/pyloh/preprocess/run_preprocess.py", line 98, in convert
    counts_tuple_list = pool.map(process_by_segment, args_list)
  File "/home/klrl262/miniconda/envs/bcbio-test/lib/python2.7/multiprocessing/pool.py", line 251, in map
Preprocessing segment chr12_start_0_end_133851895...
    return self.map_async(func, iterable, chunksize).get()
  File "/home/klrl262/miniconda/envs/bcbio-test/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
AttributeError: 'pysam.calignmentfile.PileupRead' object has no attribute 'qpos'
```
